FROM python:3.9

ENV TZ=America/Sao_Paulo
ADD ./app /app
WORKDIR /app

RUN echo $TZ > /etc/timezone
RUN apt update && apt install -y tzdata
RUN rm /etc/localtime && \
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
dpkg-reconfigure -f noninteractive tzdata && \
apt clean

RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile

CMD ["python", "worker.py"]